### ISSUE TITLE
Game freezes on loading screen

### ISSUE THREAD

**Issue by syzygy2896** [TathanDev/SkyAesthetics#19]
![Screenshot 2024-12-13 164323](https://github.com/user-attachments/assets/e3380592-218e-49c6-991b-1ea104a10410)

This happens in all versions of the mod, in Minecraft Java Fabric 1.21.1.

**Comment by TathanDev** [comment]
Make sure that your resource pack has no error.
You can find errors in the log. Also, feel free to send the logs/resourcepack, I can check for errors !

**Comment by itsdinkd** [comment]
> Make sure that your resource pack has no error. You can find errors in the log. Also, feel free to send the logs/resourcepack, I can check for errors !

```
[29Jan2025 14:21:29.085] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: No key sky_objects in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key sky_color in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key sky_type in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key stars in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key custom_vanilla_objects in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key rain in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key cloud_settings in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key world in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at MC-BOOTSTRAP/fml_loader@4.0.35/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.35.jar%23116!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.35/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.35.jar%23116!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.35/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.35.jar%23116!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.35/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.35.jar%23116!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23133!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23133!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23133!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23133!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23133!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23133!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23133!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
Caused by: java.lang.IllegalStateException: No key sky_objects in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key sky_color in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key sky_type in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key stars in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key custom_vanilla_objects in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key rain in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key cloud_settings in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]; No key world in MapLike[{"schemaVersion":2,"type":"single-sprite-square-textured","texture":"stellarity:sky/end.png","blend":{"type":"alpha"},"properties":{"priority":1,"fade":{"startFadeIn":1000,"endFadeIn":2000,"startFadeOut":3000,"endFadeOut":4000,"alwaysOn":true},"rotation":{"rotationSpeedY":0.866,"static":[0.0,0.0,0.0],"axis":[45.0,-180.0,45.0]},"transitionInDuration":60,"transitionOutDuration":60,"changeFog":true,"fogColors":{"red":0.05,"green":0,"blue":0.05,"alpha":1.0},"sunSkyTint":false,"inThickFog":true,"minAlpha":0.0,"maxAlpha":1.0},"conditions":{"worlds":[],"dimensions":["minecraft:the_end"],"weather":[],"biomes":[],"xRanges":[],"yRanges":[],"zRanges":[],"loop":{},"effects":[]},"decorations":{"blend":{"type":"decorations"},"sun":"minecraft:textures/environment/sun.png","moon":"minecraft:textures/environment/moon_phases.png","showSun":false,"showMoon":false,"showStars":true}}]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23142!/:?]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23142!/:?]
	at TRANSFORMER/sky_aesthetics@1.4.0/fr.tathan.sky_aesthetics.client.data.SkyPropertiesData.lambda$apply$0(SkyPropertiesData.java:31) ~[sky-aesthetics-1.4.0-neoforge.jar%231043!/:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at TRANSFORMER/sky_aesthetics@1.4.0/fr.tathan.sky_aesthetics.client.data.SkyPropertiesData.apply(SkyPropertiesData.java:29) ~[sky-aesthetics-1.4.0-neoforge.jar%231043!/:?]
	at TRANSFORMER/sky_aesthetics@1.4.0/fr.tathan.sky_aesthetics.client.data.SkyPropertiesData.apply(SkyPropertiesData.java:18) ~[sky-aesthetics-1.4.0-neoforge.jar%231043!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$1(SimplePreparableReloadListener.java:19) ~[client-1.21.1-20240808.144430-srg.jar%23545!/:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 24 more
```

**Comment by TathanDev** [comment]
The mod is trying to load a sky that has not the good format. If you want to make a sky using sky aesthetics, i recommend you to use https://misode.github.io/immersive-weathering/block-growth/

**Comment by st0x0ef** [comment]
I think you should maybe use this one instead, it will work better 😉 

https://misode.github.io/sky-aesthetics/sky/

**Comment by weegeeluigi** [comment]
For anyone else getting this and not making a custom sky, a conflicting mod may also crash Sky Asthetics and throw the same type of error.  In my case, it was trying out a new mod called thebygone dimension.

**Comment by itsdinkd** [comment]
> The mod is trying to load a sky that has not the good format. If you want to make a sky using sky aesthetics, i recommend you to use https://misode.github.io/immersive-weathering/block-growth/

The problem is that sky aesthetics is forcing a specific format / key pairs and if it's not as it expects, it causes a crash. The modpack loads fine when sky aesthetics is removed, even if a mods datapack doesn't contain a specific property in its sky. Can you maybe instead of telling people to create their own sky's for mods that isn't theirs to not force sky aesthetics to crash if no certain keypair is detected?

**Comment by weegeeluigi** [comment]
> > The mod is trying to load a sky that has not the good format. If you want to make a sky using sky aesthetics, i recommend you to use https://misode.github.io/immersive-weathering/block-growth/
> 
> The problem is that sky aesthetics is forcing a specific format / key pairs for all mods even if they don't use sky aesthetics as a dependent and if it's not as it expects, it causes a crash.
> 
> The modpack loads fine when sky aesthetics is removed, even if a mods resourcepack doesn't contain a specific property in its sky (which would make sense if mods create custom skies through their own means and not through sky aesthetics). Can you maybe instead of telling people to create their own sky's for mods that isn't theirs to not force sky aesthetics to crash if no certain keypair is detected?
> 
> ie: if we take my crash log, no sky_objects should not cause sky aesthetics to crash due to not being found since said mod doesn't use sky aesthetics.

Honestly I fully agree with this, a mod should be compatible in not bombing when it's not being used but assuming certain objects are there for it to use.  Bygone is probably doing something with skies that conflicts with Sky Asthetics in making it think it's being used so it bombs with that mod.  It should be transparent to mods that don't use it and not crash.  There should also be a config that allows you to disable customization for the overworld, nether and end.  My use case for this is because it's embedded in Stellaris, but I hate the fact it's creating stuff or other dimensions and my only recourse is waste time making custom resource packs vs just changing an option that disables it for the default minecraft dimensions.

**Comment by TathanDev** [comment]
I need to verify if bygone use sky as one of the folders for something in the mod and if yes i will change the folder names to sky_aesthetics to stop crash With others mods.

Also i can surely stop the game from freezing when the sky doesn't have the good format. I was using the same thing as vanilla code but i can easily change .

**Comment by weegeeluigi** [comment]
> I need to verify if bygone use sky as one of the folders for something in the mod and if yes i will change the folder names to sky_aesthetics to stop crash With others mods.
> 
> Also i can surely stop the game from freezing when the sky doesn't have the good format. I was using the same thing as vanilla code but i can easily change .

Yeah this is perfect, what you're doing should be compatible through "irrelevancy" for lack of a better word, for mods that don't use it.  I actually am interested in creating some custom skies so I do like you rmod and what it's doing.

This is off topic, but how do I disable overworld,nether and end skies?  It's conflicting with other mods and I want to disable the sun and moon and starts for the default minecraft dimensions.
